id: I3B3BF097
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:07:10+00:00'
last_modified: '2022-06-08T03:32:35.968696+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23723
  title: རྒྱ་ཆེན་བཀའ་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    534F:
      image_group_id: I2580
      title: ''
      total_pages: 1014
      order: 1
      base_file: 534F.txt
    EB88:
      image_group_id: I2581
      title: ''
      total_pages: 1040
      order: 2
      base_file: EB88.txt
    A71E:
      image_group_id: I2582
      title: ''
      total_pages: 966
      order: 3
      base_file: A71E.txt
    '6247':
      image_group_id: I2583
      title: ''
      total_pages: 1272
      order: 4
      base_file: 6247.txt
    A2D6:
      image_group_id: I2584
      title: ''
      total_pages: 1202
      order: 5
      base_file: A2D6.txt
    F325:
      image_group_id: I2585
      title: ''
      total_pages: 1164
      order: 6
      base_file: F325.txt
    12F4:
      image_group_id: I2586
      title: ''
      total_pages: 1148
      order: 7
      base_file: 12F4.txt
    20F2:
      image_group_id: I2587
      title: ''
      total_pages: 806
      order: 8
      base_file: 20F2.txt
    F371:
      image_group_id: I2588
      title: ''
      total_pages: 758
      order: 9
      base_file: F371.txt
    '0131':
      image_group_id: I2589
      title: ''
      total_pages: 882
      order: 10
      base_file: 0131.txt
    C54F:
      image_group_id: I2590
      title: ''
      total_pages: 708
      order: 11
      base_file: C54F.txt
    4DBC:
      image_group_id: I2591
      title: ''
      total_pages: 1000
      order: 12
      base_file: 4DBC.txt
    6FB6:
      image_group_id: I2592
      title: ''
      total_pages: 956
      order: 13
      base_file: 6FB6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
