id: P005502
initial_creation_type: ocr
source_metadata:
  id: bdr:W23723
  title: རྒྱ་ཆེན་བཀའ་མཛོད
  author: ''
  volumes:
    02e2734f860a4c44ba8b5141cbc6b262:
      image_group_id: I2580
      title: ''
      volume_number: 1
      total_pages: 1014
      base_file: v001.txt
    a33a81abe7424fa48202517c0c546006:
      image_group_id: I2581
      title: ''
      volume_number: 2
      total_pages: 1040
      base_file: v002.txt
    a1518984e85848e080d5776d8dc2e7b7:
      image_group_id: I2582
      title: ''
      volume_number: 3
      total_pages: 966
      base_file: v003.txt
    2c07e17608d342cd895be58f0b6be3c9:
      image_group_id: I2583
      title: ''
      volume_number: 4
      total_pages: 1272
      base_file: v004.txt
    dd690e31fbf841ecbd0ae1ba2f3e2fcd:
      image_group_id: I2584
      title: ''
      volume_number: 5
      total_pages: 1202
      base_file: v005.txt
    4278996620d04129ac028852056c8f72:
      image_group_id: I2585
      title: ''
      volume_number: 6
      total_pages: 1164
      base_file: v006.txt
    9d16922ce4e247d8a85895513edade45:
      image_group_id: I2586
      title: ''
      volume_number: 7
      total_pages: 1148
      base_file: v007.txt
    b32b949e3bf64d728e7d434063410f3a:
      image_group_id: I2587
      title: ''
      volume_number: 8
      total_pages: 806
      base_file: v008.txt
    5c3cc3aaece84187a6ed24efa5ca30a6:
      image_group_id: I2588
      title: ''
      volume_number: 9
      total_pages: 758
      base_file: v009.txt
    83c2ea0e627a440eadd18d73df535c04:
      image_group_id: I2589
      title: ''
      volume_number: 10
      total_pages: 882
      base_file: v010.txt
    097a3cfd66124dbb8cff92ecea797922:
      image_group_id: I2590
      title: ''
      volume_number: 11
      total_pages: 708
      base_file: v011.txt
    3ccc794e378644be887a962d2e2b0841:
      image_group_id: I2591
      title: ''
      volume_number: 12
      total_pages: 1000
      base_file: v012.txt
    424b8a28687f41e6ab32015163ab9244:
      image_group_id: I2592
      title: ''
      volume_number: 13
      total_pages: 956
      base_file: v013.txt
